package tasks

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.ProjectLayout
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.CompileClasspath
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations
import java.io.File
import java.util.Properties
import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream
import javax.inject.Inject

abstract class DexPluginTask : DefaultTask() {

    @get:InputFile
    abstract val inputJar: RegularFileProperty

    @get:OutputFile
    abstract val outputJar: RegularFileProperty

    @get:CompileClasspath
    abstract val classpath: ConfigurableFileCollection

    @get:Inject
    abstract val execOperations: ExecOperations

    @get:Inject
    abstract val layout: ProjectLayout

    @get:Internal
    val sdkDir: File by lazy {
        val properties = Properties()
        val localProperties = layout.projectDirectory.file("local.properties").asFile
        if (localProperties.exists()) {
            localProperties.inputStream().use { properties.load(it) }
        }
        val path = properties.getProperty("sdk.dir")
            ?: System.getenv("ANDROID_HOME")
            ?: throw GradleException(
                "Android SDK not found. Set sdk.dir in local.properties or ANDROID_HOME environment variable."
            )
        File(path)
    }

    @TaskAction
    fun execute() {
        val buildToolsDir = File(sdkDir, "build-tools")
        val latestBuildTool = buildToolsDir.listFiles()
            ?.filter { it.isDirectory }
            ?.maxByOrNull { it.name }
            ?: throw GradleException("No build-tools found in ${buildToolsDir.absolutePath}")

        val d8Executable = if (System.getProperty("os.name").lowercase().contains("win")) {
            File(latestBuildTool, "d8.bat")
        } else {
            File(latestBuildTool, "d8")
        }

        if (!d8Executable.exists()) {
            throw GradleException("d8 executable not found at ${d8Executable.absolutePath}")
        }

        val platformsDir = File(sdkDir, "platforms")
        val latestPlatform = platformsDir.listFiles()
            ?.filter { it.isDirectory && File(it, "android.jar").exists() }
            ?.maxByOrNull { it.name }
        val androidJar = latestPlatform?.let { File(it, "android.jar") }

        val tempDir = layout.buildDirectory.dir("tmp/dex").get().asFile.apply {
            deleteRecursively()
            mkdirs()
        }

        val inputJarFile = inputJar.get().asFile
        val outputJarFile = outputJar.get().asFile
        val d8Args = mutableListOf(
            d8Executable.absolutePath,
            "--release",
            "--min-api", "21",
            "--output", tempDir.absolutePath,
        )
        if (androidJar != null) {
            d8Args += listOf("--lib", androidJar.absolutePath)
        }
        classpath.files.filter { it.exists() }.forEach { jar ->
            d8Args += listOf("--classpath", jar.absolutePath)
        }
        d8Args += inputJarFile.absolutePath

        execOperations.exec {
            commandLine(d8Args)
        }

        val dexFiles = tempDir.listFiles { _, name -> name.endsWith(".dex") } ?: emptyArray()
        if (dexFiles.isEmpty()) {
            throw GradleException("No dex files generated by d8")
        }

        // keep resources for Tachiyomi extensions
        ZipOutputStream(outputJarFile.outputStream()).use { zos ->
            dexFiles.forEach { dexFile ->
                zos.putNextEntry(ZipEntry(dexFile.name))
                dexFile.inputStream().use { it.copyTo(zos) }
                zos.closeEntry()
            }
            ZipFile(inputJarFile).use { zip ->
                zip.entries().asSequence().forEach { entry ->
                    val name = entry.name
                    if (!name.endsWith(".class") && name != "META-INF/MANIFEST.MF") {
                        if (entry.isDirectory) {
                            zos.putNextEntry(ZipEntry(name))
                            zos.closeEntry()
                        } else {
                            zos.putNextEntry(ZipEntry(name))
                            zip.getInputStream(entry).use { it.copyTo(zos) }
                            zos.closeEntry()
                        }
                    }
                }
            }
        }
    }
}